program_name: Fedora Summer Coding 2010
admin_name: Karsten Wade
admin_designation: Program Administrator

fsoc_mode: Summer Coding

auth_via_script: true
account_system: Fedora Account System
account_system_uri: https://admin.fedoraproject.org/accounts


