programname: Fedora Summer Coding 2010
adminname: Karsten Wade
admindesignation: Program Administrator

fsocmode: Summer Coding

authviascript: true
scriptcommand: ruby lib/checkpassword.rb
accountsystem: Fedora Account System
accountsystemuri: https://admin.fedoraproject.org/accounts

timeframesset: false
pct_from:
pct_to:
pst_from:
pst_to:
pat_from:
pat_to:
csd_on:
met_from:
met_to:
ced_on:
fet_from:
fet_to:
