--- 
auth: 
  module: 
timeframes: 
  set: false
admin: 
  name: Abc Xyz
  designation: Program Administrator
  username: admin
  password: random
  email: someaddress@someorg.org
fsoc: 
  mode: year_round
program: 
  name: Four Seasons of Code
  name_abbreviation: FSoC
  edition: "2010"
